### ISSUE TITLE
Get-Jobs returns invalid response

### ISSUE THREAD

**Issue by jameshalsall** [OpenPrinting/goipp#2]
Consider the following code:

```go
req := goipp.NewRequest(goipp.DefaultVersion, goipp.OpGetJobs, 1)
req.Operation.Add(goipp.MakeAttribute("attributes-charset", goipp.TagCharset, "utf-8"))
req.Operation.Add(goipp.MakeAttribute("attributes-natural-language", goipp.TagLanguage, "en-US"))
req.Operation.Add(goipp.MakeAttribute("which-jobs", goipp.TagKeyword, goipp.String("not-completed")))

// send request
```

**What I get**
The response is
```
Attributes: [
  {
    "Name": "job-id",
    "Values": [
      {
        "T": 33,
        "V": 128
      }
    ]
  },
  {
    "Name": "job-uri",
    "Values": [
      {
        "T": 69,
        "V": "ipps://EPSONB44453.local.:631/jobs/128"
      }
    ]
  },
  {
    "Name": "job-id",
    "Values": [
      {
        "T": 33,
        "V": 127
      }
    ]
  },
  {
    "Name": "job-uri",
    "Values": [
      {
        "T": 69,
        "V": "ipps://EPSONB44453.local.:631/jobs/127"
      }
    ]
  }
]
```

**What I expect to get**
The response should be logically grouped by the job. Currently we get 4 separate attributes and no easy way to tie them together, there should be a logical grouping as described in the [spec](https://www.rfc-editor.org/rfc/rfc2911#section-3.2.6.2):
> The Printer object responds with one set of Job Object Attributes for each returned Job object

**Comment by jameshalsall** [comment]
Having thought about this some more, and the scope of this repository, this is probably expected behaviour. I'll close.

**Comment by alexpevzner** [comment]
Hi @jameshalsall,

please, have a look to discussion under #3 and change https://github.com/OpenPrinting/goipp/commit/1be44245b302d00bfc92f081b5750fddec503edf
